[build]
  publish = "."
  functions = "netlify/functions"

# Long cache for static assets
[[headers]]
  for = "/apps/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

# Security headers (basic CSP example; adjust if adding external scripts)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), geolocation=(), microphone=()"

# Optional redirects for pretty URLs
[[redirects]]
  from = "/creatorhub"
  to = "/apps/creatorhub-mini-plus/"
  status = 301

[[redirects]]
  from = "/studio"
  to = "/apps/studio-express-ia/"
  status = 301

[[redirects]]
  from = "/prompt"
  to = "/apps/prompt-designer-pro/"
  status = 301

[[redirects]]
  from = "/logo"
  to = "/apps/logo-flash-ai/"
  status = 301

[[redirects]]
  from = "/caption"
  to = "/apps/caption-craft/"
  status = 301
