version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sylius
      POSTGRES_PASSWORD: sylius
      POSTGRES_DB: sylius
    ports: ["5433:5432"]
  php:
    image: php:8.2-apache
    volumes: ["./:/var/www/html"]
    depends_on: [db]
    ports: ["8081:80"]
