name: Gemini CURL Smoketest
on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: Show curl version
        run: curl --version
      - name: One-line POST (no backslashes)
        shell: bash
        run: |
          set -euo pipefail
          test -n "${GEMINI_API_KEY}" || (echo "Missing GEMINI_API_KEY" && exit 1)
          curl -sS -X POST -H "x-goog-api-key: ${GEMINI_API_KEY}" -H "Content-Type: application/json" "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent" -d '{"contents":[{"parts":[{"text":"Ping monoligne."}]}]}' | tee smoke.json
          grep -q '"candidates"' smoke.json && echo "OK"
