version: "3.8"
services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    ports: ["3306:3306"]
  web:
    image: prestashop/prestashop:latest
    environment:
      PS_DEV_MODE: 1
    depends_on: [db]
    ports: ["8080:80"]
