[build]
  publish = "public"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-inline-functions-env"

[headers]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
