---
name: Parlios - Agents AutoSync

"on":
  issues:
    types: [labeled]        # déclenche uniquement quand on ajoute un label
  workflow_dispatch: {}     # lancement manuel

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  from_issue_to_pr:
    if: ${{ github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'agent:new' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Extract JSON from Issue body
        id: extract
        env:
          BODY: ${{ github.event.issue.body }}
        run: |
          # récupère un bloc ```json ... ``` s'il existe
          printf "%s" "$BODY" | awk '/```json/{flag=1;next}/```/{flag=0}flag' > /tmp/agent.json || true
          # sinon, prend tout le corps
          if [ ! -s /tmp/agent.json ]; then
            printf "%s" "$BODY" > /tmp/agent.json || true
          fi
          # valide JSON
          if ! jq empty /tmp/agent.json 2>/dev/null; then
            echo "Issue body n'est pas un JSON valide. Mets un bloc ```json ... ```"
            exit 1
          fi

      - name: Prepare working tree
        run: |
          mkdir -p modules
          MOD="modules/WebCreationTeam.json"
          test -f "$MOD" || echo '{"agents":[]}' > "$MOD"
          if jq -e 'type=="array"' /tmp/agent.json >/dev/null; then
            jq --slurpfile new /tmp/agent.json '.agents += $new' "$MOD" > "$MOD.tmp"
          else
            jq --slurpfile new /tmp/agent.json '.agents += [$new[0]]' "$MOD" > "$MOD.tmp"
          fi
          mv "$MOD.tmp" "$MOD"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add agent from issue #${{ github.event.issue.number }}"
          branch: "auto/agent-${{ github.event.issue.number }}-${{ github.run_id }}"
          title: "AutoSync: agent from issue #${{ github.event.issue.number }}"
          body: "Auto-generated from issue #${{ github.event.issue.number }}."
          delete-branch: true
