      - name: Scaffold agent from templates
        run: |
          set -e
          SLUG="${{ steps.pl.outputs.slug }}"
          NAME="${{ steps.pl.outputs.name }}"
          ROLE="${{ steps.pl.outputs.role }}"
          AG_DIR="agents/$SLUG"
          KP_DIR="knowledge/agents/$SLUG"

          if [ -d "agents/_template" ]; then
            mkdir -p "$AG_DIR"
            rsync -a "agents/_template/" "$AG_DIR/" --exclude ".gitkeep" || true
          else
            mkdir -p "$AG_DIR/workflows"
            cat > "$AG_DIR/manifest.json" <<JSON
          { "name": "$NAME", "slug": "$SLUG", "version": "1.0.0" }
JSON
            cat > "$AG_DIR/README.md" <<'MD'
# $NAME
Rôle: $ROLE
MD
          fi
