name: UA Bot – Auto Comment on Cleanup PR

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  auto-comment:
    if: contains(github.event.pull_request.title, 'chore(ua-cleanup'))
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add cleanup reminder comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          gh api \
            repos/${REPO}/issues/${PR_NUMBER}/comments \
            -f body='### 🤖 UA Bot – Post-merge Reminder

Merci d’avoir lancé le nettoyage sécurisé 🧹  
Une fois cette PR fusionnée :

1. Accède à **Actions → Cleanup Artifacts (manual)**  
2. Clique sur **Run workflow**  
3. Renseigne la variable `keep_days` (par défaut : `7`)  
   → Cela supprimera automatiquement les artifacts CI/CD plus anciens que 7 jours.

💡 _Ce workflow ne touche pas aux fichiers sources et peut être relancé à tout moment._'
