name: Gemini Streaming
on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: Show runner info
        shell: bash
        run: |
          uname -a
          bash --version | head -n1

      - name: Define URL (and sanitize CRLF)
        id: url
        shell: bash
        run: |
          set -euo pipefail
          URL_RAW="https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:streamGenerateContent?alt=sse"
          # Supprime tout \r éventuel (CRLF) qui casse curl
          URL=$(printf "%s" "$URL_RAW" | tr -d '\r')
          echo "url=$URL" >> "$GITHUB_OUTPUT"
          echo "Using URL: $URL"

      - name: Stream tokens (SSE)
        shell: bash
        run: |
          set -euo pipefail
          test -n "${GEMINI_API_KEY:-}" || { echo "❌ Missing GEMINI_API_KEY secret"; exit 2; }
          URL="${{ steps.url.outputs.url }}"
          echo ">>> Streaming depuis: $URL"
          curl -N -sS "$URL" \
            -H "x-goog-api-key: $GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            --data-binary @- <<'JSON'
{
  "contents": [
    { "parts": [ { "text": "Donne 5 punchlines courtes (format liste)." } ] }
  ]
}
JSON
          echo
          echo ">>> Fin du streaming ✅"
