name: Gemini Streaming
on: { workflow_dispatch: {} }
jobs:
  stream:
    runs-on: ubuntu-latest
    env: { GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} }
    steps:
      - name: Stream tokens
        run: |
          # Astuce: -N pour ne pas bufferiser, on lit les events au fil de l'eau
          curl -N -sS "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:streamGenerateContent?alt=sse" \
            -H "x-goog-api-key: $GEMINI_API_KEY" -H "Content-Type: application/json" \
            -d '{"contents":[{"parts":[{"text":"Donne 5 punchlines courtes."}]}]}'
