name: Netlify Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ⬇️ Remplace par TON build réel si besoin (Vite/Next/etc.)
      - name: Build bundle (exemple minimal)
        run: |
          mkdir -p dist
          cat > dist/index.html <<'EOF'
          <!doctype html>
          <html><head><meta charset='utf-8'><title>Parlios</title></head>
          <body><h1>Parlios — GO Preprod</h1></body></html>
          EOF
          echo "/*    /index.html   200" > dist/_redirects
          printf "User-agent: *\nAllow: /\nSitemap: https://parlios.netlify.app/sitemap.xml\n" > dist/robots.txt

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Deploy to Netlify (prod)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          PARLIOS_SITE_ID: ${{ secrets.PARLIOS_SITE_ID }}
        run: |
          if [ -n "$PARLIOS_SITE_ID" ]; then
            netlify deploy --dir dist --site "$PARLIOS_SITE_ID" --prod --json > DEPLOY_LOG.json
          else
            netlify deploy --dir dist --prod --json > DEPLOY_LOG.json
          fi
          echo "DEPLOY_URL=$(jq -r '.url' DEPLOY_LOG.json)" >> $GITHUB_ENV
          echo "DEPLOY_LOG:"
          cat DEPLOY_LOG.json

      - name: Upload deploy log
        uses: actions/upload-artifact@v4
        with:
          name: deploy-log
          path: DEPLOY_LOG.json
