name: QA Web (Lighthouse+Pa11y+Linkinator)

on:
  pull_request:
    # On ne déclenche QUE si les changements touchent le site ou ce workflow
    paths:
      - "site/**"
      - "web/**"
      - ".github/workflows/qa_web.yml"

jobs:
  qa:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installe Node pour les outils CLI (lighthouse, pa11y, linkinator)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install QA tools
        run: |
          npm i -g lighthouse@12 pa11y@6 linkinator@5 serve@14

      # Build du site si nécessaire (adapter la commande à ton projet)
      - name: Build site
        run: |
          if [ -d "site" ]; then
            cd site
            if [ -f "package.json" ]; then
              npm ci || npm i
              npm run build || echo "No build script, skipping"
            fi
            cd ..
          fi

      # Lance un serveur local pour auditer (adapter le dossier si besoin)
      - name: Start static server
        run: |
          nohup npx serve ./site/dist -l 4173 >/dev/null 2>&1 &
          sleep 2

      - name: Lighthouse
        run: |
          npx lighthouse http://127.0.0.1:4173 --quiet --chrome-flags="--headless" --only-categories=performance,accessibility,best-practices,seo --preset=desktop --output=json --output-path=./lighthouse.json
          echo "Lighthouse done."

      - name: Pa11y (AA)
        run: |
          npx pa11y http://127.0.0.1:4173 --standard WCAG2AA --timeout 60000
          echo "Pa11y done."

      - name: Linkinator
        run: |
          npx linkinator http://127.0.0.1:4173 --timeout=5000 --retry --concurrency=10
          echo "Linkinator done."

      - name: Upload Lighthouse artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-qa-lighthouse
          path: ./lighthouse.json
