name: Release Auto

on:
  workflow_dispatch:
    inputs:
      version:
        description: "vX.Y.Z"
        required: true
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Ensure tag (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Generate notes
        id: notes
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
