name: Security – Snyk (SCA)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Install Node deps (if package.json)
        if: hashFiles('**/package.json') != ''
        run: npm ci --ignore-scripts --fund=false --audit=false

      - name: Install Python deps (if requirements.txt)
        if: hashFiles('**/requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Snyk Open Source (SCA) – JSON
        run: snyk test --all-projects --json-file-output=snyk-os.json || true

      - name: Snyk monitor (snapshot in Snyk UI)
        run: snyk monitor --all-projects || true

      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snyk-reports
          path: snyk-os.json
          if-no-files-found: ignore
