name: UA AutoMerge
on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'UA_Orchestrator' || contains(github.event.pull_request.labels.*.name, 'automate')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Auto-merge approved PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.UA_ORCHESTRATOR_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: automate, orchestrator
          MERGE_COMMIT_MESSAGE: |
            Auto-merged by UA_Orchestrator after CI validation.
          MERGE_DELETE_BRANCH: true
