      - name: Valider la clé (présence/forme)
        id: validate
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          set -e
          if [ -z "${GEMINI_API_KEY:-}" ]; then
            echo "❌ Secret GEMINI_API_KEY introuvable. Vérifie Settings → Secrets → Actions (repository)." >&2
            exit 3
          fi
          # Trim soft (supprime CR/LF + espaces autour)
          CLEANED="$(printf "%s" "$GEMINI_API_KEY" | tr -d '\r' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
          if [ "${#CLEANED}" -lt 20 ]; then
            echo "❌ Clé trop courte ou mal collée. Recolle la clé depuis AI Studio dans le secret." >&2
            exit 4
          fi
          echo "::notice::GEMINI_API_KEY chargé (longueur: ${#CLEANED})"
