name: Gemini Ping

on:
  workflow_dispatch:
  push:
    paths: [".github/workflows/gemini-ping.yml"]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Show model answer (REST)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          set -e
          echo 'Calling Gemini…'
          curl -s "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent" \
            -H "x-goog-api-key: $GEMINI_API_KEY" \
            -H "Content-Type: application/json" \
            -X POST \
            -d '{
                  "contents":[{"parts":[{"text":"Dis bonjour à Max (une phrase)."}]}]
                }' | tee response.json

          # Affiche un extrait lisible (optionnel si jq présent)
          if command -v jq >/dev/null 2>&1; then
            jq -r '.candidates[0].content.parts[0].text // "No text found"' response.json
          else
            echo "Astuce: installe jq pour un output plus propre"
          fi
